# Generated by Django 3.2.6 on 2021-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40, null=True)),
                ('Email', models.EmailField(max_length=40, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
