# Generated by Django 3.2.6 on 2021-09-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0002_user_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Model',
        ),
    ]
