# Generated by Django 3.2.6 on 2021-10-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0008_auto_20211007_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='shippmenst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
